kibana:
  resources:
    requests:
      cpu: 1
      memory: 1024Mi
    limits:
      cpu: 2
      memory: 1524Mi
  elasticsearch:
    hosts:
      - elasticsearch.observability.svc.cluster.local
    port: 9200
    security:
      auth:
        enabled: true
        elasticsearchPasswordSecret: elasticsearch-admin
