---
replicaCount: 1
resources:
  requests:
    cpu: 2
    memory: 512Mi
  limits:
    cpu: 3
    memory: 1024Mi
containerPorts:
  - name: http
    containerPort: 8080
    protocol: TCP
extraEnvVars:
  - name: ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-admin
        key: elasticsearch-password

input: |-
  http { port => 8080 }

filter: |-
  if [@metadata][input-http] {
    date {
      match => [ "date", "UNIX" ]
      remove_field => [ "date" ]
    }
    mutate {
      remove_field => ["headers","host"]
    }
  }

output: |-
  elasticsearch {
    hosts => ["http://lab-elasticsearch.observability.svc.cluster.local:9200"]
    # index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "${ES_PASSWORD}"
  }
